
import { CreditCard, SpendingProfile } from './types';

// Helper to create a flat rate reward
const flat = (rate: number, cap?: number) => ({ rate, cap });

export const CREDIT_CARDS: CreditCard[] = [
  // ==================== HDFC BANK ====================
  {
    id: 'hdfc-infinia',
    name: 'HDFC Infinia Metal Edition',
    bank: 'HDFC Bank',
    imageUrl: 'https://www.hdfcbank.com/content/api/contentstream-id/723fb80a-2dde-42a3-9793-7ae1be57c87f/f8d67280-9978-4389-9b97-154df2e21b77/Infinia_Metal_Card_264x167.png',
    joiningFee: 12500,
    annualFee: 12500,
    feeWaiver: 'Waived on ₹10L annual spend',
    waiverThreshold: 1000000,
    joiningBonus: '12,500 Reward Points',
    features: ['3.3% Base Reward Rate', 'Up to 33% on SmartBuy', 'Unlimited Lounge Access', 'Golf Privileges'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.033),
      amazon: flat(0.033),
      otherOnline: flat(0.033),
      grocery: flat(0.033),
      utilities: flat(0.033),
      fuel: flat(0),
      dining: flat(0.066),
      movies: flat(0.033),
      travel: flat(0.165),
      offline: flat(0.033),
    },
    sharedCaps: [{ categories: ['travel'], cap: 15000 }]
  },
  {
    id: 'hdfc-diners-black',
    name: 'HDFC Diners Club Black Metal',
    bank: 'HDFC Bank',
    imageUrl: 'https://www.hdfcbank.com/content/api/contentstream-id/723fb80a-2dde-42a3-9793-7ae1be57c87f/d8717808-1662-4b2a-89a3-5c66d2138977/Diners%20Club%20Black%20Metal%20Edition%20Credit%20Card_264x167.png',
    joiningFee: 10000,
    annualFee: 10000,
    feeWaiver: 'Waived on ₹8L annual spend',
    waiverThreshold: 800000,
    joiningBonus: '10,000 Reward Points',
    features: ['3.33% Base Rate', 'Unlimited Lounges', 'Up to 10X on SmartBuy'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.033),
      amazon: flat(0.033),
      otherOnline: flat(0.033),
      grocery: flat(0.033),
      utilities: flat(0.033),
      fuel: flat(0),
      dining: flat(0.066),
      movies: flat(0.033),
      travel: flat(0.165),
      offline: flat(0.033),
    },
    sharedCaps: [{ categories: ['travel'], cap: 10000 }]
  },
  {
    id: 'hdfc-regalia-gold',
    name: 'HDFC Regalia Gold',
    bank: 'HDFC Bank',
    imageUrl: 'https://www.hdfcbank.com/content/api/contentstream-id/723fb80a-2dde-42a3-9793-7ae1be57c87f/2a50787d-8153-46aa-9d8a-63cb53d10008/Regalia%20Gold%20Credit%20Card_264x167.png',
    joiningFee: 2500,
    annualFee: 2500,
    feeWaiver: 'Waived on ₹4L annual spend',
    waiverThreshold: 400000,
    joiningBonus: 'M&S/Reliance/Myntra Voucher ₹1500',
    features: ['4 Reward Points per ₹150', '5X on Marks & Spencer, Myntra, Nykaa'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.026),
      amazon: flat(0.026),
      otherOnline: flat(0.026),
      grocery: flat(0.026),
      utilities: flat(0.026),
      fuel: flat(0),
      dining: flat(0.026),
      movies: flat(0.026),
      travel: flat(0.026),
      offline: flat(0.026),
    }
  },
  {
    id: 'hdfc-millennia',
    name: 'HDFC Millennia Credit Card',
    bank: 'HDFC Bank',
    imageUrl: 'https://www.hdfcbank.com/content/api/contentstream-id/723fb80a-2dde-42a3-9793-7ae1be57c87f/a3240e83-7188-4674-8911-c30c804f8e02/Millennia%20CC_264x167.png',
    joiningFee: 1000,
    annualFee: 1000,
    feeWaiver: 'Waived on ₹1L annual spend',
    waiverThreshold: 100000,
    joiningBonus: '1000 CashPoints',
    features: ['5% Cashback on Amazon, Flipkart, Swiggy, Zomato', '1% on others'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.05),
      amazon: flat(0.05),
      otherOnline: flat(0.01),
      grocery: flat(0.01),
      utilities: flat(0.01),
      fuel: flat(0),
      dining: flat(0.05),
      movies: flat(0.05),
      travel: flat(0.05),
      offline: flat(0.01),
    },
    sharedCaps: [{ categories: ['flipkart', 'amazon', 'dining', 'movies', 'travel'], cap: 1000 }]
  },
  {
    id: 'hdfc-swiggy',
    name: 'Swiggy HDFC Bank Credit Card',
    bank: 'HDFC Bank',
    imageUrl: 'https://www.hdfcbank.com/content/api/contentstream-id/723fb80a-2dde-42a3-9793-7ae1be57c87f/9f50a80e-3603-4f01-9878-361718f456e3/Swiggy%20Credit%20Card_264x167.png',
    joiningFee: 500,
    annualFee: 500,
    feeWaiver: 'Waived on ₹2L annual spend',
    waiverThreshold: 200000,
    joiningBonus: '3 Months Swiggy One',
    features: ['10% Cashback on Swiggy', '5% on Amazon, Flipkart', '1% others'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.05),
      amazon: flat(0.05),
      otherOnline: flat(0.05),
      grocery: flat(0.10),
      utilities: flat(0.01),
      fuel: flat(0),
      dining: flat(0.10),
      movies: flat(0.05),
      travel: flat(0.05),
      offline: flat(0.01),
    },
    sharedCaps: [
      { categories: ['grocery', 'dining'], cap: 1500 },
      { categories: ['flipkart', 'amazon', 'otherOnline', 'movies', 'travel'], cap: 1500 }
    ]
  },
  {
    id: 'hdfc-tata-neu-infinity',
    name: 'HDFC Tata Neu Infinity',
    bank: 'HDFC Bank',
    imageUrl: 'https://www.hdfcbank.com/content/api/contentstream-id/723fb80a-2dde-42a3-9793-7ae1be57c87f/7360e53d-2495-4674-8b89-2a9d82121e7d/Tata%20Neu%20Infinity%20HDFC%20Bank%20Credit%20Card_264x167.png',
    joiningFee: 1499,
    annualFee: 1499,
    feeWaiver: 'Waived on ₹3L annual spend',
    waiverThreshold: 300000,
    joiningBonus: '1499 NeuCoins',
    features: ['10% NeuCoins on Tata Neu App', '5% on Tata Brands', '1.5% on others'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.015),
      amazon: flat(0.015),
      otherOnline: flat(0.05),
      grocery: flat(0.05),
      utilities: flat(0.015),
      fuel: flat(0),
      dining: flat(0.015),
      movies: flat(0.015),
      travel: flat(0.05),
      offline: flat(0.015),
    }
  },
  {
    id: 'hdfc-tata-neu-plus',
    name: 'HDFC Tata Neu Plus',
    bank: 'HDFC Bank',
    imageUrl: 'https://www.hdfcbank.com/content/api/contentstream-id/723fb80a-2dde-42a3-9793-7ae1be57c87f/8a53e34b-fb62-4c28-98e6-12822a559869/Tata%20Neu%20Plus%20HDFC%20Bank%20Credit%20Card_264x167.png',
    joiningFee: 499,
    annualFee: 499,
    feeWaiver: 'Waived on ₹1L annual spend',
    waiverThreshold: 100000,
    joiningBonus: '499 NeuCoins',
    features: ['7% NeuCoins on Tata Neu App', '2% on Tata Brands', '1% on others'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.01),
      amazon: flat(0.01),
      otherOnline: flat(0.02),
      grocery: flat(0.02),
      utilities: flat(0.01),
      fuel: flat(0),
      dining: flat(0.01),
      movies: flat(0.01),
      travel: flat(0.02),
      offline: flat(0.01),
    }
  },
  {
    id: 'hdfc-moneyback-plus',
    name: 'HDFC MoneyBack+ Credit Card',
    bank: 'HDFC Bank',
    imageUrl: 'https://www.hdfcbank.com/content/api/contentstream-id/723fb80a-2dde-42a3-9793-7ae1be57c87f/5457c79f-8647-495c-9c9c-230588636b04/MoneyBack%20Plus%20Credit%20Card_264x167.png',
    joiningFee: 500,
    annualFee: 500,
    feeWaiver: 'Waived on ₹50k annual spend',
    waiverThreshold: 50000,
    joiningBonus: '500 CashPoints',
    features: ['10X CashPoints on Amazon, BigBasket, Flipkart, Swiggy', '5X on EMI'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.033),
      amazon: flat(0.033),
      otherOnline: flat(0.003),
      grocery: flat(0.033),
      utilities: flat(0.003),
      fuel: flat(0),
      dining: flat(0.033),
      movies: flat(0.003),
      travel: flat(0.003),
      offline: flat(0.003),
    },
    sharedCaps: [{ categories: ['flipkart', 'amazon', 'grocery', 'dining'], cap: 2500 }]
  },

  // ==================== SBI CARDS ====================
  {
    id: 'sbi-cashback',
    name: 'Cashback SBI Card',
    bank: 'SBI Card',
    imageUrl: 'https://www.sbicard.com/sbi-card-en/assets/media/images/personal/credit-cards/lifestyle/cashback-sbi-card/card-face-image-cashback-sbi-card.png',
    joiningFee: 999,
    annualFee: 999,
    feeWaiver: 'Waived on ₹2L annual spend',
    waiverThreshold: 200000,
    joiningBonus: 'None',
    features: ['5% Cashback on almost all online spends', '1% on offline spends'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.05),
      amazon: flat(0.05),
      otherOnline: flat(0.05),
      grocery: flat(0.05),
      utilities: flat(0),
      fuel: flat(0),
      dining: flat(0.05),
      movies: flat(0.05),
      travel: flat(0.05),
      offline: flat(0.01),
    },
    sharedCaps: [{ categories: ['flipkart', 'amazon', 'otherOnline', 'grocery', 'dining', 'movies', 'travel'], cap: 5000 }]
  },
  {
    id: 'sbi-prime',
    name: 'SBI Card PRIME',
    bank: 'SBI Card',
    imageUrl: 'https://www.sbicard.com/sbi-card-en/assets/media/images/personal/credit-cards/lifestyle/sbi-card-prime/card-face-image-sbi-card-prime.png',
    joiningFee: 2999,
    annualFee: 2999,
    feeWaiver: 'Waived on ₹3L annual spend',
    waiverThreshold: 300000,
    joiningBonus: '₹3000 E-Gift Voucher',
    features: ['10 Reward Points per ₹100 on Dining, Groceries', '4 Lounge Visits/Year'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.005),
      amazon: flat(0.005),
      otherOnline: flat(0.005),
      grocery: flat(0.025),
      utilities: flat(0.025),
      fuel: flat(0),
      dining: flat(0.025),
      movies: flat(0.025),
      travel: flat(0.005),
      offline: flat(0.005),
    }
  },
  {
    id: 'sbi-elite',
    name: 'SBI Card ELITE',
    bank: 'SBI Card',
    imageUrl: 'https://www.sbicard.com/sbi-card-en/assets/media/images/personal/credit-cards/lifestyle/sbi-card-elite/card-face-image-sbi-card-elite.png',
    joiningFee: 4999,
    annualFee: 4999,
    feeWaiver: 'Waived on ₹10L annual spend',
    waiverThreshold: 1000000,
    joiningBonus: '₹5000 E-Gift Voucher',
    features: ['5X Rewards on Dining, Grocery', '2 Free Movie Tickets/month', '6 Intl Lounge Visits'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.005),
      amazon: flat(0.005),
      otherOnline: flat(0.005),
      grocery: flat(0.0125),
      utilities: flat(0.005),
      fuel: flat(0),
      dining: flat(0.0125),
      movies: flat(0.005),
      travel: flat(0.005),
      offline: flat(0.005),
    }
  },
  {
    id: 'sbi-simplyclick',
    name: 'SBI SimplyCLICK Credit Card',
    bank: 'SBI Card',
    imageUrl: 'https://www.sbicard.com/sbi-card-en/assets/media/images/personal/credit-cards/shopping/simplyclick-sbi-card/card-face-image-simplyclick-sbi-card.png',
    joiningFee: 499,
    annualFee: 499,
    feeWaiver: 'Waived on ₹1L annual spend',
    waiverThreshold: 100000,
    joiningBonus: '₹500 Amazon Voucher',
    features: ['10X Rewards on Partners', '5X on all other online spends'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.0125),
      amazon: flat(0.0125),
      otherOnline: flat(0.0125),
      grocery: flat(0.0125),
      utilities: flat(0),
      fuel: flat(0),
      dining: flat(0.025),
      movies: flat(0.025),
      travel: flat(0.025),
      offline: flat(0.0025),
    }
  },

  // ==================== AXIS BANK ====================
  {
    id: 'axis-magnus',
    name: 'Axis Bank Magnus',
    bank: 'Axis Bank',
    imageUrl: 'https://www.axisbank.com/images/default-source/revamp_new/cards/credit-cards/desktop/magnus-credit-card.jpg',
    joiningFee: 12500,
    annualFee: 12500,
    feeWaiver: 'Waived on ₹25L annual spend',
    waiverThreshold: 2500000,
    joiningBonus: 'Voucher worth ₹12,500',
    features: ['12 Points per ₹200', 'Unlimited Domestic Lounge', '5X on Travel Edge'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.024),
      amazon: flat(0.024),
      otherOnline: flat(0.024),
      grocery: flat(0.024),
      utilities: flat(0),
      fuel: flat(0),
      dining: flat(0.024),
      movies: flat(0.024),
      travel: flat(0.12),
      offline: flat(0.024),
    }
  },
  {
    id: 'axis-atlas',
    name: 'Axis Bank ATLAS',
    bank: 'Axis Bank',
    imageUrl: 'https://www.axisbank.com/images/default-source/revamp_new/cards/credit-cards/desktop/atlas-credit-card.jpg',
    joiningFee: 5000,
    annualFee: 5000,
    feeWaiver: 'Not applicable',
    waiverThreshold: undefined,
    joiningBonus: '5000 EDGE Miles',
    features: ['5 Miles per ₹100 on Travel', '2 Miles per ₹100 Base', 'Milestone Benefits'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.02),
      amazon: flat(0.02),
      otherOnline: flat(0.02),
      grocery: flat(0.02),
      utilities: flat(0),
      fuel: flat(0),
      dining: flat(0.02),
      movies: flat(0.02),
      travel: flat(0.05),
      offline: flat(0.02),
    }
  },
  {
    id: 'axis-flipkart',
    name: 'Flipkart Axis Bank Credit Card',
    bank: 'Axis Bank',
    imageUrl: 'https://www.axisbank.com/images/default-source/revamp_new/cards/credit-cards/desktop/flipkart-axis-bank-credit-card.jpg',
    joiningFee: 500,
    annualFee: 500,
    feeWaiver: 'Waived on ₹3.5L annual spend',
    waiverThreshold: 350000,
    joiningBonus: '₹500 Flipkart Voucher',
    features: ['5% Unlimited Cashback on Flipkart', '4% on Swiggy, Uber', '1.5% on other spends'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.05),
      amazon: flat(0.015),
      otherOnline: flat(0.015),
      grocery: flat(0.015),
      utilities: flat(0),
      fuel: flat(0),
      dining: flat(0.04),
      movies: flat(0.04),
      travel: flat(0.04),
      offline: flat(0.015),
    }
  },
  {
    id: 'axis-ace',
    name: 'Axis Bank ACE Credit Card',
    bank: 'Axis Bank',
    imageUrl: 'https://www.axisbank.com/images/default-source/revamp_new/cards/credit-cards/desktop/ace-credit-card.jpg',
    joiningFee: 499,
    annualFee: 499,
    feeWaiver: 'Waived on ₹2L annual spend',
    waiverThreshold: 200000,
    joiningBonus: 'None',
    features: ['5% Cashback on Bills (GPay)', '4% on Swiggy, Zomato', '2% Unlimited on others'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.02),
      amazon: flat(0.02),
      otherOnline: flat(0.02),
      grocery: flat(0.02),
      utilities: flat(0.05, 500),
      fuel: flat(0),
      dining: flat(0.04),
      movies: flat(0.02),
      travel: flat(0.04),
      offline: flat(0.02),
    }
  },
  {
    id: 'axis-airtel',
    name: 'Airtel Axis Bank Credit Card',
    bank: 'Axis Bank',
    imageUrl: 'https://www.axisbank.com/images/default-source/revamp_new/cards/credit-cards/desktop/airtel-axis-bank-credit-card.jpg',
    joiningFee: 500,
    annualFee: 500,
    feeWaiver: 'Waived on ₹2L annual spend',
    waiverThreshold: 200000,
    joiningBonus: '₹500 Amazon Voucher',
    features: ['25% on Airtel Bills', '10% on BigBasket, Swiggy, Zomato', '10% on Utilities'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.01),
      amazon: flat(0.01),
      otherOnline: flat(0.01),
      grocery: flat(0.10),
      utilities: flat(0.10),
      fuel: flat(0),
      dining: flat(0.10),
      movies: flat(0.01),
      travel: flat(0.01),
      offline: flat(0.01),
    },
    sharedCaps: [
      { categories: ['utilities'], cap: 300 },
      { categories: ['grocery', 'dining'], cap: 500 }
    ]
  },

  // ==================== ICICI BANK ====================
  {
    id: 'icici-emeralde',
    name: 'ICICI Bank Emeralde Private Metal',
    bank: 'ICICI Bank',
    imageUrl: 'https://www.icicibank.com/content/dam/icicibank/india/managed-assets/images/credit-card/emeralde-credit-card-private-metal.png',
    joiningFee: 12499,
    annualFee: 12499,
    feeWaiver: 'Waived on ₹15L spend',
    waiverThreshold: 1500000,
    joiningBonus: '12500 Reward Points',
    features: ['6 Points per ₹200', 'Unlimited Lounges', 'Low Forex 1.99%'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.03),
      amazon: flat(0.03),
      otherOnline: flat(0.03),
      grocery: flat(0.03),
      utilities: flat(0.03),
      fuel: flat(0.01),
      dining: flat(0.03),
      movies: flat(0.03),
      travel: flat(0.03),
      offline: flat(0.03),
    }
  },
  {
    id: 'icici-amazon',
    name: 'Amazon Pay ICICI Credit Card',
    bank: 'ICICI Bank',
    imageUrl: 'https://www.icicibank.com/content/dam/icicibank/india/managed-assets/images/credit-card/amazon-pay-credit-card.png',
    joiningFee: 0,
    annualFee: 0,
    feeWaiver: 'Lifetime Free',
    waiverThreshold: 0,
    joiningBonus: '₹2000 Rewards',
    features: ['5% Cashback on Amazon (Prime)', '2% on Flights', '1% Flat on others', 'Lifetime Free'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.01),
      amazon: flat(0.05),
      otherOnline: flat(0.01),
      grocery: flat(0.01),
      utilities: flat(0.02),
      fuel: flat(0),
      dining: flat(0.01),
      movies: flat(0.01),
      travel: flat(0.02),
      offline: flat(0.01),
    }
  },
  {
    id: 'icici-ruby',
    name: 'ICICI Bank Rubyx Credit Card',
    bank: 'ICICI Bank',
    imageUrl: 'https://www.icicibank.com/content/dam/icicibank/india/managed-assets/images/credit-card/rubyx-credit-card.png',
    joiningFee: 2000,
    annualFee: 2000,
    feeWaiver: 'Waived on ₹3L spend',
    waiverThreshold: 300000,
    joiningBonus: '₹5000 Vouchers',
    features: ['2X Rewards on International', 'BOGO Movies'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.005),
      amazon: flat(0.005),
      otherOnline: flat(0.005),
      grocery: flat(0.005),
      utilities: flat(0.005),
      fuel: flat(0),
      dining: flat(0.005),
      movies: flat(0.01),
      travel: flat(0.005),
      offline: flat(0.005),
    }
  },

  // ==================== AMEX ====================
  {
    id: 'amex-platinum',
    name: 'American Express Platinum Card',
    bank: 'American Express',
    imageUrl: 'https://icm.aexp-static.com/Internet/InternationalCardShop/va_in/images/cards/Platinum_Card.png',
    joiningFee: 66000,
    annualFee: 66000,
    feeWaiver: 'Not applicable',
    waiverThreshold: undefined,
    joiningBonus: '135,000 MR Points',
    features: ['Unlimited Global Lounge Access', '3X on International Spends', 'Platinum Concierge', 'Marriott Gold Status'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.02), // 1 pt per 50
      amazon: flat(0.02),
      otherOnline: flat(0.02),
      grocery: flat(0.02),
      utilities: flat(0.02),
      fuel: flat(0),
      dining: flat(0.02),
      movies: flat(0.02),
      travel: flat(0.06), // 3X on Intl
      offline: flat(0.02),
    }
  },
  {
    id: 'amex-platinum-travel',
    name: 'American Express Platinum Travel',
    bank: 'American Express',
    imageUrl: 'https://icm.aexp-static.com/Internet/InternationalCardShop/va_in/images/cards/Platinum_Travel.png',
    joiningFee: 3500,
    annualFee: 5000,
    feeWaiver: 'Not applicable',
    waiverThreshold: undefined,
    joiningBonus: '10,000 MR Points',
    features: ['40,000 MR Points + ₹10K Voucher on ₹4L Spend', '4 Lounge Visits', 'Taj Vouchers'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.01),
      amazon: flat(0.01),
      otherOnline: flat(0.01),
      grocery: flat(0.01),
      utilities: flat(0),
      fuel: flat(0),
      dining: flat(0.01),
      movies: flat(0.01),
      travel: flat(0.01),
      offline: flat(0.01),
    }
  },
  {
    id: 'amex-gold',
    name: 'American Express Gold Charge',
    bank: 'American Express',
    imageUrl: 'https://icm.aexp-static.com/Internet/InternationalCardShop/va_in/images/cards/Gold_Charge.png',
    joiningFee: 1000,
    annualFee: 4500,
    feeWaiver: 'Not applicable',
    waiverThreshold: undefined,
    joiningBonus: '4000 Membership Rewards',
    features: ['5X on Reward Multiplier', '1000 Bonus Points for 6x1000 txns', 'No pre-set limit'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.02),
      amazon: flat(0.02),
      otherOnline: flat(0.02),
      grocery: flat(0.02),
      utilities: flat(0.02),
      fuel: flat(0),
      dining: flat(0.02),
      movies: flat(0.02),
      travel: flat(0.02),
      offline: flat(0.02),
    }
  },
  {
    id: 'amex-mrcc',
    name: 'American Express MRCC',
    bank: 'American Express',
    imageUrl: 'https://icm.aexp-static.com/Internet/InternationalCardShop/va_in/images/cards/Membership_Rewards_Credit_Card.png',
    joiningFee: 1000,
    annualFee: 4500,
    feeWaiver: 'Waived on ₹1.5L spend',
    waiverThreshold: 150000,
    joiningBonus: '4000 MR Points',
    features: ['1000 Bonus MR on 4x1500 txns', '1000 Bonus MR on ₹20k spend', '2 MR per ₹100'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.01),
      amazon: flat(0.01),
      otherOnline: flat(0.01),
      grocery: flat(0.01),
      utilities: flat(0.01),
      fuel: flat(0),
      dining: flat(0.01),
      movies: flat(0.01),
      travel: flat(0.01),
      offline: flat(0.01),
    }
  },
  {
    id: 'amex-smart-earn',
    name: 'American Express SmartEarn',
    bank: 'American Express',
    imageUrl: 'https://icm.aexp-static.com/Internet/InternationalCardShop/va_in/images/cards/SmartEarn_Card.png',
    joiningFee: 495,
    annualFee: 495,
    feeWaiver: 'Waived on ₹40k spend',
    waiverThreshold: 40000,
    joiningBonus: '₹500 Cashback',
    features: ['10X on Flipkart, Uber, Zomato', '5X on Amazon, Myntra', 'Low Fee'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.05, 500),
      amazon: flat(0.025, 250),
      otherOnline: flat(0.005),
      grocery: flat(0.005),
      utilities: flat(0.005),
      fuel: flat(0),
      dining: flat(0.05, 500),
      movies: flat(0.005),
      travel: flat(0.05, 500),
      offline: flat(0.005),
    }
  },

  // ==================== IDFC FIRST ====================
  {
    id: 'idfc-wealth',
    name: 'IDFC FIRST Wealth Credit Card',
    bank: 'IDFC First Bank',
    imageUrl: 'https://www.idfcfirstbank.com/content/dam/idfcfirstbank/images/credit-card/wealth-card.png',
    joiningFee: 0,
    annualFee: 0,
    feeWaiver: 'Lifetime Free',
    waiverThreshold: 0,
    joiningBonus: '₹500 Voucher',
    features: ['10X Rewards > ₹30k Spend', 'Low Forex 1.5%', 'BOGO Movies', 'Lifetime Free'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.025),
      amazon: flat(0.025),
      otherOnline: flat(0.015),
      grocery: flat(0.015),
      utilities: flat(0.0025),
      fuel: flat(0),
      dining: flat(0.015),
      movies: flat(0.015),
      travel: flat(0.015),
      offline: flat(0.0075),
    }
  },
  {
    id: 'idfc-select',
    name: 'IDFC FIRST Select Credit Card',
    bank: 'IDFC First Bank',
    imageUrl: 'https://www.idfcfirstbank.com/content/dam/idfcfirstbank/images/credit-card/select-card.png',
    joiningFee: 0,
    annualFee: 0,
    feeWaiver: 'Lifetime Free',
    waiverThreshold: 0,
    joiningBonus: '₹500 Voucher',
    features: ['10X Rewards > ₹25k Spend', 'BOGO Movies', '4 Lounge Visits'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.025),
      amazon: flat(0.025),
      otherOnline: flat(0.015),
      grocery: flat(0.015),
      utilities: flat(0.0025),
      fuel: flat(0),
      dining: flat(0.015),
      movies: flat(0.015),
      travel: flat(0.015),
      offline: flat(0.0075),
    }
  },

  // ==================== SC ====================
  {
    id: 'sc-ultimate',
    name: 'Standard Chartered Ultimate',
    bank: 'Standard Chartered',
    imageUrl: 'https://av.sc.com/in/content/images/in-ultimate-credit-card-kv-400x250.jpg',
    joiningFee: 5000,
    annualFee: 5000,
    feeWaiver: 'Not applicable',
    waiverThreshold: undefined,
    joiningBonus: '6000 Reward Points',
    features: ['3.3% Reward Rate on All Spends', '5% on Duty Free', 'Low Forex 2%'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.033),
      amazon: flat(0.033),
      otherOnline: flat(0.033),
      grocery: flat(0.033),
      utilities: flat(0.033),
      fuel: flat(0.033),
      dining: flat(0.033),
      movies: flat(0.033),
      travel: flat(0.033),
      offline: flat(0.033),
    }
  },
  {
    id: 'sc-smart',
    name: 'Standard Chartered Smart',
    bank: 'Standard Chartered',
    imageUrl: 'https://av.sc.com/in/content/images/in-smart-credit-card-kv-400x250.jpg',
    joiningFee: 499,
    annualFee: 499,
    feeWaiver: 'Waived on ₹1.2L spend',
    waiverThreshold: 120000,
    joiningBonus: 'None',
    features: ['2% Cashback on Online Spends', '1% on Offline', 'Interest-free cash withdrawal 90 days'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.02, 1000),
      amazon: flat(0.02, 1000),
      otherOnline: flat(0.02, 1000),
      grocery: flat(0.02, 1000),
      utilities: flat(0.02, 1000),
      fuel: flat(0),
      dining: flat(0.02, 1000),
      movies: flat(0.02, 1000),
      travel: flat(0.02, 1000),
      offline: flat(0.01),
    }
  },

  // ==================== HSBC ====================
  {
    id: 'hsbc-cashback',
    name: 'HSBC Cashback Credit Card',
    bank: 'HSBC',
    imageUrl: 'https://www.hsbc.co.in/content/dam/hsbc/in/images/credit-cards/cashback-credit-card.png',
    joiningFee: 999,
    annualFee: 999,
    feeWaiver: 'Waived on ₹2L spend',
    waiverThreshold: 200000,
    joiningBonus: '₹1000 Amazon Voucher',
    features: ['10% Cashback on Dining, Food Delivery, Grocery', '1.5% Unlimited on others', '4 Lounge Visits'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.015),
      amazon: flat(0.015),
      otherOnline: flat(0.015),
      grocery: flat(0.10, 1000),
      utilities: flat(0),
      fuel: flat(0),
      dining: flat(0.10, 1000),
      movies: flat(0.015),
      travel: flat(0.015),
      offline: flat(0.015),
    }
  },

  // ==================== KOTAK ====================
  {
    id: 'kotak-white',
    name: 'Kotak White Credit Card',
    bank: 'Kotak Mahindra Bank',
    imageUrl: 'https://www.kotak.com/content/dam/Kotak/product_card_images/white-credit-card-front.png',
    joiningFee: 3000,
    annualFee: 3000,
    feeWaiver: 'Waived on ₹5L spend',
    waiverThreshold: 500000,
    joiningBonus: '₹1500 White Pass',
    features: ['White Pass Value on Spends', 'Premium Travel Benefits'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.015),
      amazon: flat(0.015),
      otherOnline: flat(0.015),
      grocery: flat(0.015),
      utilities: flat(0.015),
      fuel: flat(0),
      dining: flat(0.015),
      movies: flat(0.015),
      travel: flat(0.015),
      offline: flat(0.015),
    }
  },
  {
    id: 'kotak-myntra',
    name: 'Myntra Kotak Credit Card',
    bank: 'Kotak Mahindra Bank',
    imageUrl: 'https://www.kotak.com/content/dam/Kotak/product_card_images/myntra-kotak-credit-card-front.png',
    joiningFee: 500,
    annualFee: 500,
    feeWaiver: 'Waived on ₹2L spend',
    waiverThreshold: 200000,
    joiningBonus: '₹500 Myntra Voucher',
    features: ['7.5% Instant Discount on Myntra', '5% Cashback on Swiggy, PVR, Cleartrip', '1.25% on others'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.0125),
      amazon: flat(0.0125),
      otherOnline: flat(0.0125),
      grocery: flat(0.0125),
      utilities: flat(0.0125),
      fuel: flat(0),
      dining: flat(0.05),
      movies: flat(0.05),
      travel: flat(0.05),
      offline: flat(0.0125),
    }
  },

  // ==================== YES BANK ====================
  {
    id: 'yes-marquee',
    name: 'YES Marquee Credit Card',
    bank: 'YES Bank',
    imageUrl: 'https://www.yesbank.in/pdf/marquee_credit_card_image.pdf',
    joiningFee: 9999,
    annualFee: 4999,
    feeWaiver: 'Not applicable',
    waiverThreshold: undefined,
    joiningBonus: '60,000 Reward Points',
    features: ['4.5% Reward Rate Online', 'Unlimited Lounges', 'BOGO Movies', 'Low Forex 1%'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.045),
      amazon: flat(0.045),
      otherOnline: flat(0.045),
      grocery: flat(0.0225),
      utilities: flat(0.0225),
      fuel: flat(0),
      dining: flat(0.0225),
      movies: flat(0.045),
      travel: flat(0.045),
      offline: flat(0.0225),
    }
  },
  
  // ==================== AU BANK ====================
  {
    id: 'au-zenith-plus',
    name: 'AU Zenith+ Credit Card',
    bank: 'AU Small Finance Bank',
    imageUrl: 'https://www.aubank.in/assets/images/credit-card/zenith-plus-credit-card-front.png',
    joiningFee: 4999,
    annualFee: 4999,
    feeWaiver: 'Waived on ₹8L spend',
    waiverThreshold: 800000,
    joiningBonus: '5000 Reward Points',
    features: ['2 Reward Points per ₹100', 'Lowest Forex 0.99%', '16 Domestic Lounges'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.01),
      amazon: flat(0.01),
      otherOnline: flat(0.01),
      grocery: flat(0.01),
      utilities: flat(0.01),
      fuel: flat(0),
      dining: flat(0.02),
      movies: flat(0.01),
      travel: flat(0.02),
      offline: flat(0.01),
    }
  },

  // ==================== INDUSIND ====================
  {
    id: 'indusind-legend',
    name: 'IndusInd Legend Credit Card',
    bank: 'IndusInd Bank',
    imageUrl: 'https://www.indusind.com/content/dam/indusind-platform-images/product-images/personal-banking/cards/credit-cards/legend-credit-card/legend-card-image.png',
    joiningFee: 0,
    annualFee: 0,
    feeWaiver: 'Lifetime Free',
    waiverThreshold: 0,
    joiningBonus: 'None',
    features: ['1 Reward Point per ₹100', '2X on Weekends', 'Lifetime Free'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.01),
      amazon: flat(0.01),
      otherOnline: flat(0.01),
      grocery: flat(0.01),
      utilities: flat(0.0075),
      fuel: flat(0),
      dining: flat(0.01),
      movies: flat(0.01),
      travel: flat(0.01),
      offline: flat(0.0075),
    }
  },
  
  // ==================== RBL ====================
  {
    id: 'rbl-world-safari',
    name: 'RBL World Safari Credit Card',
    bank: 'RBL Bank',
    imageUrl: 'https://www.rblbank.com/sites/default/files/2019-09/world-safari-card-face.png',
    joiningFee: 3000,
    annualFee: 3000,
    feeWaiver: 'Not applicable',
    waiverThreshold: undefined,
    joiningBonus: '₹3000 MMT Voucher',
    features: ['0% Forex Markup', '5X on Travel', '2 Lounge Visits'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.01),
      amazon: flat(0.01),
      otherOnline: flat(0.01),
      grocery: flat(0.01),
      utilities: flat(0.01),
      fuel: flat(0),
      dining: flat(0.01),
      movies: flat(0.01),
      travel: flat(0.05),
      offline: flat(0.01),
    }
  },
  
  // ==================== BOB ====================
  {
    id: 'bob-eterna',
    name: 'BOB Eterna Credit Card',
    bank: 'Bank of Baroda',
    imageUrl: 'https://www.bobfinancial.com/images/Eterna-Card-Face.png',
    joiningFee: 2499,
    annualFee: 2499,
    feeWaiver: 'Waived on ₹2.5L spend',
    waiverThreshold: 250000,
    joiningBonus: 'FitPass Pro',
    features: ['3.75% on Online Travel, Dining, Movie', 'Unlimited Lounges'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.0075),
      amazon: flat(0.0075),
      otherOnline: flat(0.0075),
      grocery: flat(0.0075),
      utilities: flat(0.0075),
      fuel: flat(0.01),
      dining: flat(0.0375),
      movies: flat(0.0375),
      travel: flat(0.0375),
      offline: flat(0.0075),
    }
  },

  // ==================== FEDERAL ====================
  {
    id: 'scapia',
    name: 'Scapia Federal Bank Card',
    bank: 'Federal Bank',
    imageUrl: 'https://www.scapia.cards/assets/images/card_front.png',
    joiningFee: 0,
    annualFee: 0,
    feeWaiver: 'Lifetime Free',
    waiverThreshold: 0,
    joiningBonus: 'None',
    features: ['Zero Forex Markup', '10% Coins on Travel (In-app)', '2% Coins on all other spends'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.02),
      amazon: flat(0.02),
      otherOnline: flat(0.02),
      grocery: flat(0.02),
      utilities: flat(0),
      fuel: flat(0),
      dining: flat(0.02),
      movies: flat(0.02),
      travel: flat(0.04),
      offline: flat(0.02),
    }
  }
];

export const INITIAL_SPENDING_PROFILE: SpendingProfile = {
    flipkart: 0,
    amazon: 0,
    otherOnline: 0,
    grocery: 0,
    utilities: 0,
    fuel: 0,
    dining: 0,
    movies: 0,
    travel: 0,
    offline: 0,
};
