
import { CreditCard, SpendingProfile } from './types';

// Helper to create a flat rate reward
const flat = (rate: number, cap?: number) => ({ rate, cap });

export const CREDIT_CARDS: CreditCard[] = [
  // ==================== SBI CARDS ====================
  {
    id: 'sbi-cashback',
    name: 'Cashback SBI Card',
    bank: 'SBI Card',
    imageUrl: 'https://www.sbicard.com/sbi-card-en/assets/media/images/personal/credit-cards/lifestyle/cashback-sbi-card/card-face-image-cashback-sbi-card.png',
    joiningFee: 999,
    annualFee: 999,
    feeWaiver: 'Waived on ₹2L annual spend',
    waiverThreshold: 200000,
    joiningBonus: 'None',
    features: ['5% Cashback on almost all online spends', '1% on offline spends', 'No merchant restrictions (except exclusions)'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.05, 5000),
      amazon: flat(0.05, 5000),
      otherOnline: flat(0.05, 5000),
      grocery: flat(0.05, 5000), // Online grocery included
      utilities: flat(0), 
      fuel: flat(0), 
      dining: flat(0.05, 5000), // Online food delivery
      movies: flat(0.05, 5000), // Online booking
      travel: flat(0.05, 5000),
      offline: flat(0.01),
    },
  },
  {
    id: 'sbi-simply-click',
    name: 'SimplyCLICK SBI Card',
    bank: 'SBI Card',
    imageUrl: 'https://www.sbicard.com/sbi-card-en/assets/media/images/personal/credit-cards/shopping/simplyclick-sbi-card/card-face-image-simplyclick-sbi-card.png',
    joiningFee: 499,
    annualFee: 499,
    feeWaiver: 'Waived on ₹1L annual spend',
    waiverThreshold: 100000,
    joiningBonus: '₹500 Amazon Voucher',
    features: ['10X Rewards on Apollo, BookMyShow, Cleartrip, Domino’s, Myntra', '5X on all other online spends', '1% fuel surcharge waiver'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.0125), // 5X = 1.25%
      amazon: flat(0.0125), // 5X
      otherOnline: flat(0.0125), // 5X
      grocery: flat(0.0125),
      utilities: flat(0),
      fuel: flat(0),
      dining: flat(0.025), // 10X Domino's etc (approx 2.5%)
      movies: flat(0.025), // 10X BMS
      travel: flat(0.025), // 10X Cleartrip
      offline: flat(0.0025), // 1X
    },
  },
  {
    id: 'sbi-simply-save',
    name: 'SimplySAVE SBI Card',
    bank: 'SBI Card',
    imageUrl: 'https://www.sbicard.com/sbi-card-en/assets/media/images/personal/credit-cards/shopping/simplysave-sbi-card/card-face-image-simplysave-sbi-card.png',
    joiningFee: 499,
    annualFee: 499,
    feeWaiver: 'Waived on ₹1L annual spend',
    waiverThreshold: 100000,
    joiningBonus: '2000 Bonus Points (₹500 value)',
    features: ['10X Reward Points on Dining, Movies, Grocery & Dept Stores', '1 Reward Point per ₹150 on other spends', '1% Fuel Surcharge Waiver'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.0025), // 1 Point/150 = 0.25% (Base)
      amazon: flat(0.0025),
      otherOnline: flat(0.0025),
      grocery: flat(0.025), // 10X = 2.5%
      utilities: flat(0.0025),
      fuel: flat(0),
      dining: flat(0.025), // 10X = 2.5%
      movies: flat(0.025), // 10X = 2.5%
      travel: flat(0.0025),
      offline: flat(0.0025),
    },
  },
  {
    id: 'sbi-prime',
    name: 'SBI Card PRIME',
    bank: 'SBI Card',
    imageUrl: 'https://www.sbicard.com/sbi-card-en/assets/media/images/personal/credit-cards/lifestyle/sbi-card-prime/card-face-image-sbi-card-prime.png',
    joiningFee: 2999,
    annualFee: 2999,
    feeWaiver: 'Waived on ₹3L annual spend',
    waiverThreshold: 300000,
    joiningBonus: '₹3,000 Gift Voucher',
    features: ['20 Reward Points per ₹100 on Utility Bill Payments', '10 Points per ₹100 on Dining, Groceries, Movies', 'Club Vistara Silver Membership'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.005), // 2 RP/100 = 0.5%
      amazon: flat(0.005),
      otherOnline: flat(0.005),
      grocery: flat(0.025), // 10 RP/100 = 2.5%
      utilities: flat(0.05, 3000), // 20 RP/100 = 5% (Capped)
      fuel: flat(0),
      dining: flat(0.025), // 10 RP/100 = 2.5%
      movies: flat(0.025), // 10 RP/100 = 2.5%
      travel: flat(0.005),
      offline: flat(0.005),
    },
  },
  {
    id: 'sbi-bpcl',
    name: 'BPCL SBI Card',
    bank: 'SBI Card',
    imageUrl: 'https://www.sbicard.com/sbi-card-en/assets/media/images/personal/credit-cards/travel/bpcl-sbi-card/card-face-image-bpcl-sbi-card.png',
    joiningFee: 499,
    annualFee: 499,
    feeWaiver: 'Waived on ₹50k annual spend',
    waiverThreshold: 50000,
    joiningBonus: '2000 Activation Bonus Reward Points',
    features: ['4.25% Value back on Fuel at BPCL pumps', '5X Reward Points on Groceries, Dept. Stores, Movies, Dining'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.0025),
      amazon: flat(0.0025),
      otherOnline: flat(0.0025),
      grocery: flat(0.0125), // 5X = 1.25%
      utilities: flat(0.0025),
      fuel: flat(0.0425, 1300), // 13X Reward Points on Fuel
      dining: flat(0.0125),
      movies: flat(0.0125),
      travel: flat(0.0025),
      offline: flat(0.0025),
    },
  },
  {
    id: 'sbi-elite',
    name: 'SBI Card ELITE',
    bank: 'SBI Card',
    imageUrl: 'https://www.sbicard.com/sbi-card-en/assets/media/images/personal/credit-cards/lifestyle/sbi-card-elite/card-face-image-sbi-card-elite.png',
    joiningFee: 4999,
    annualFee: 4999,
    feeWaiver: 'Waived on ₹10L annual spend',
    waiverThreshold: 1000000,
    joiningBonus: 'Welcome Gift worth ₹5,000',
    features: ['5X Reward Points on Dining, Departmental stores and Grocery', 'Complimentary Movie Tickets worth ₹6,000/year', 'Domestic & International Lounge Access'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.005),
      amazon: flat(0.005),
      otherOnline: flat(0.005),
      grocery: flat(0.025),
      utilities: flat(0.005),
      fuel: flat(0),
      dining: flat(0.025),
      movies: flat(0.025),
      travel: flat(0.005),
      offline: flat(0.005),
    },
  },

  // ==================== AXIS BANK ====================
  {
    id: 'axis-flipkart',
    name: 'Flipkart Axis Bank Credit Card',
    bank: 'Axis Bank',
    imageUrl: 'https://www.axisbank.com/images/default-source/revamp_new/cards/credit-cards/desktop/flipkart-axis-bank-credit-card.jpg',
    joiningFee: 500,
    annualFee: 500,
    feeWaiver: 'Waived on ₹3.5L annual spend',
    waiverThreshold: 350000,
    joiningBonus: '₹500 Flipkart Voucher + Swiggy benefits',
    features: ['5% Unlimited Cashback on Flipkart', '4% on Swiggy, Uber, PVR, Cleartrip', '1.5% Flat on all other spends'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.05),
      amazon: flat(0.015),
      otherOnline: flat(0.015),
      grocery: flat(0.015),
      utilities: flat(0),
      fuel: flat(0),
      dining: flat(0.04), // Swiggy
      movies: flat(0.04), // PVR
      travel: flat(0.04), // Uber/Cleartrip
      offline: flat(0.015),
    },
  },
  {
    id: 'axis-ace',
    name: 'Axis Bank ACE Credit Card',
    bank: 'Axis Bank',
    imageUrl: 'https://www.axisbank.com/images/default-source/revamp_new/cards/credit-cards/desktop/ace-credit-card.jpg',
    joiningFee: 499,
    annualFee: 499,
    feeWaiver: 'Waived on ₹2L annual spend',
    waiverThreshold: 200000,
    joiningBonus: 'None',
    features: ['5% Cashback on Bill Payments via GPay', '4% on Swiggy, Zomato, Ola', '2% Unlimited on all other spends'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.02),
      amazon: flat(0.02),
      otherOnline: flat(0.02),
      grocery: flat(0.02),
      utilities: flat(0.05, 500), // GPay bills
      fuel: flat(0),
      dining: flat(0.04), // Swiggy/Zomato
      movies: flat(0.02),
      travel: flat(0.04), // Ola
      offline: flat(0.02),
    },
  },
  {
    id: 'axis-airtel',
    name: 'Airtel Axis Bank Credit Card',
    bank: 'Axis Bank',
    imageUrl: 'https://www.axisbank.com/images/default-source/revamp_new/cards/credit-cards/desktop/airtel-axis-bank-credit-card.jpg',
    joiningFee: 500,
    annualFee: 500,
    feeWaiver: 'Waived on ₹2L annual spend',
    waiverThreshold: 200000,
    joiningBonus: '₹500 Amazon Voucher',
    features: ['25% Cashback on Airtel Mobile/Broadband/WiFi', '10% on BigBasket, Swiggy, Zomato', '10% on Utility Bills via Airtel App'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.01),
      amazon: flat(0.01),
      otherOnline: flat(0.01),
      grocery: flat(0.10, 500), // BigBasket
      utilities: flat(0.10, 300), // Airtel App / Utilities
      fuel: flat(0),
      dining: flat(0.10, 500), // Swiggy/Zomato
      movies: flat(0.01),
      travel: flat(0.01),
      offline: flat(0.01),
    },
  },
  {
    id: 'axis-myzone',
    name: 'Axis Bank MY ZONE Credit Card',
    bank: 'Axis Bank',
    imageUrl: 'https://www.axisbank.com/images/default-source/revamp_new/cards/credit-cards/desktop/my-zone-credit-card.jpg',
    joiningFee: 500,
    annualFee: 500,
    feeWaiver: 'Not applicable',
    waiverThreshold: undefined,
    joiningBonus: 'SonyLiv Premium Annual Subscription',
    features: ['Buy 1 Get 1 on Movies (Paytm)', 'Flat ₹120 off on Swiggy', 'SonyLiv Premium Subscription'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.002), // 4 EDGE points / 200 = ~0.4%
      amazon: flat(0.002),
      otherOnline: flat(0.002),
      grocery: flat(0.002),
      utilities: flat(0.002),
      fuel: flat(0),
      dining: flat(0.15, 480), // Approx 15% via Swiggy coupon (₹120 off x 4 times)
      movies: flat(0.50, 200), // BOGO capped at Rs 200
      travel: flat(0.002),
      offline: flat(0.002),
    },
  },
  {
    id: 'axis-neo',
    name: 'Axis Bank Neo Credit Card',
    bank: 'Axis Bank',
    imageUrl: 'https://www.axisbank.com/images/default-source/revamp_new/cards/credit-cards/desktop/neo-credit-card.jpg',
    joiningFee: 250,
    annualFee: 250,
    feeWaiver: 'Waived on ₹2.5L annual spend',
    waiverThreshold: 250000,
    joiningBonus: 'Amazon/Zomato Vouchers',
    features: ['40% off on Zomato', '5% off on Utility Bills (Amazon Pay)', '10% off on Blinkit'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.002),
      amazon: flat(0.002),
      otherOnline: flat(0.002),
      grocery: flat(0.10, 150), // Blinkit 10%
      utilities: flat(0.05, 150), // Amazon Pay Bills 5%
      fuel: flat(0),
      dining: flat(0.10, 240), // Zomato 40% (modeled as 10% effective avg due to caps)
      movies: flat(0.10), // BookMyShow 10%
      travel: flat(0.002),
      offline: flat(0.002),
    },
  },
  {
    id: 'axis-select',
    name: 'Axis Bank SELECT Credit Card',
    bank: 'Axis Bank',
    imageUrl: 'https://www.axisbank.com/images/default-source/revamp_new/cards/credit-cards/desktop/select-credit-card.jpg',
    joiningFee: 3000,
    annualFee: 3000,
    feeWaiver: 'Waived on ₹6L annual spend',
    waiverThreshold: 600000,
    joiningBonus: '₹2000 Amazon Voucher',
    features: ['20% off on BigBasket', '40% off on Swiggy', 'Buy 1 Get 1 on Movies'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.01), // 10 pts / 200 = 1%
      amazon: flat(0.01),
      otherOnline: flat(0.01), // 2X on Retail
      grocery: flat(0.20, 500), // 20% off BB
      utilities: flat(0.005),
      fuel: flat(0),
      dining: flat(0.40, 400), // Swiggy
      movies: flat(0.50, 300), // BOGO
      travel: flat(0.01),
      offline: flat(0.01), // 2X on Retail
    },
  },

  // ==================== HDFC BANK ====================
  {
    id: 'hdfc-millennia',
    name: 'HDFC Millennia Credit Card',
    bank: 'HDFC Bank',
    imageUrl: 'https://www.hdfcbank.com/content/api/contentstream-id/723fb80a-2dde-42a3-9793-7ae1be57c87f/a3240e83-7188-4670-8911-c30c804f8e02/Millennia%20CC_264x167.png',
    joiningFee: 1000,
    annualFee: 1000,
    feeWaiver: 'Waived on ₹1L annual spend',
    waiverThreshold: 100000,
    joiningBonus: '1000 CashPoints',
    features: ['5% Cashback on Amazon, Flipkart, BookMyShow, Cult.fit, Myntra, Sony LIV, Swiggy, Tata CLiQ, Uber, Zomato', '1% on other spends'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.05, 1000),
      amazon: flat(0.05, 1000),
      otherOnline: flat(0.01), // Only specific partners get 5%
      grocery: flat(0.01),
      utilities: flat(0.01),
      fuel: flat(0),
      dining: flat(0.05, 1000), // Swiggy/Zomato
      movies: flat(0.05, 1000), // BMS
      travel: flat(0.05, 1000), // Uber
      offline: flat(0.01),
    },
  },
  {
    id: 'hdfc-moneyback-plus',
    name: 'HDFC MoneyBack+ Credit Card',
    bank: 'HDFC Bank',
    imageUrl: 'https://www.hdfcbank.com/content/api/contentstream-id/723fb80a-2dde-42a3-9793-7ae1be57c87f/24365780-6062-4541-9430-802c6360c7f1/MoneyBack+%20Credit%20Card_264x167.png',
    joiningFee: 500,
    annualFee: 500,
    feeWaiver: 'Waived on ₹50k annual spend',
    waiverThreshold: 50000,
    joiningBonus: '500 CashPoints',
    features: ['10X CashPoints on Amazon, BigBasket, Flipkart, Reliance Smart SuperStore, Swiggy', '5X CashPoints on EMI', '2 CashPoints per ₹150 others'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.033), // 10X = ~3.3% value
      amazon: flat(0.033),
      otherOnline: flat(0.0033),
      grocery: flat(0.033), // BigBasket
      utilities: flat(0.0033),
      fuel: flat(0),
      dining: flat(0.033), // Swiggy
      movies: flat(0.0033),
      travel: flat(0.0033),
      offline: flat(0.0033),
    },
  },
  {
    id: 'hdfc-swiggy',
    name: 'Swiggy HDFC Bank Credit Card',
    bank: 'HDFC Bank',
    imageUrl: 'https://www.hdfcbank.com/content/api/contentstream-id/723fb80a-2dde-42a3-9793-7ae1be57c87f/9f50a80e-3603-4f01-9878-361718f456e3/Swiggy%20Credit%20Card_264x167.png',
    joiningFee: 500,
    annualFee: 500,
    feeWaiver: 'Waived on ₹2L annual spend',
    waiverThreshold: 200000,
    joiningBonus: '3 Months Swiggy One Membership',
    features: ['10% Cashback on Swiggy (Food, Instamart, Dineout)', '5% on Amazon, Flipkart, Myntra, Nykaa, Uber, BookMyShow', '1% on other spends'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.05, 1500),
      amazon: flat(0.05, 1500),
      otherOnline: flat(0.05, 1500), // Myntra, Nykaa included
      grocery: flat(0.10, 1500), // Swiggy Instamart
      utilities: flat(0.01),
      fuel: flat(0),
      dining: flat(0.10, 1500), // Swiggy Food/Dineout
      movies: flat(0.05, 1500), // BMS
      travel: flat(0.05, 1500), // Uber
      offline: flat(0.01),
    },
  },
  {
    id: 'hdfc-tata-neu-infinity',
    name: 'Tata Neu Infinity HDFC Bank',
    bank: 'HDFC Bank',
    imageUrl: 'https://www.hdfcbank.com/content/api/contentstream-id/723fb80a-2dde-42a3-9793-7ae1be57c87f/56e729a4-5777-40e9-b684-2a6642d99d98/Tata%20Neu%20Infinity%20HDFC%20Bank%20Credit%20Card_264x167.png',
    joiningFee: 1499,
    annualFee: 1499,
    feeWaiver: 'Waived on ₹3L annual spend',
    waiverThreshold: 300000,
    joiningBonus: '1499 NeuCoins',
    features: ['10% NeuCoins on Tata Neu App', '5% on Tata Brands (Croma, BigBasket, Titan)', '1.5% on other spends', 'Complimentary Lounge Access'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.015),
      amazon: flat(0.015),
      otherOnline: flat(0.05), // Assuming spending on Tata brands (Croma/Titan)
      grocery: flat(0.05), // BigBasket
      utilities: flat(0.015),
      fuel: flat(0),
      dining: flat(0.015),
      movies: flat(0.015),
      travel: flat(0.05), // AirAsia/IHCL
      offline: flat(0.015),
    },
  },
  {
    id: 'hdfc-tata-neu-plus',
    name: 'Tata Neu Plus HDFC Bank',
    bank: 'HDFC Bank',
    imageUrl: 'https://www.hdfcbank.com/content/api/contentstream-id/723fb80a-2dde-42a3-9793-7ae1be57c87f/e442d8f2-e5b1-4d3e-90ce-75184281e411/Tata%20Neu%20Plus%20HDFC%20Bank%20Credit%20Card_264x167.png',
    joiningFee: 499,
    annualFee: 499,
    feeWaiver: 'Waived on ₹1L annual spend',
    waiverThreshold: 100000,
    joiningBonus: '499 NeuCoins',
    features: ['7% NeuCoins on Tata Neu App', '2% on Tata Brands', '1% on other spends'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.01),
      amazon: flat(0.01),
      otherOnline: flat(0.02), // Tata Brands
      grocery: flat(0.02), // BigBasket
      utilities: flat(0.01),
      fuel: flat(0),
      dining: flat(0.01),
      movies: flat(0.01),
      travel: flat(0.02), // AirAsia
      offline: flat(0.01),
    },
  },
  {
    id: 'hdfc-freedom',
    name: 'HDFC Freedom Credit Card',
    bank: 'HDFC Bank',
    imageUrl: 'https://www.hdfcbank.com/content/api/contentstream-id/723fb80a-2dde-42a3-9793-7ae1be57c87f/3f3f5087-9477-43c3-9426-3453b320d32f/Freedom%20Credit%20Card_264x167.png',
    joiningFee: 500,
    annualFee: 500,
    feeWaiver: 'Waived on ₹50k annual spend',
    waiverThreshold: 50000,
    joiningBonus: '500 CashPoints',
    features: ['10X CashPoints on BigBasket, BookMyShow, OYO, Swiggy, Uber', '5X on EMI', '1 CashPoint per ₹150 others'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.001),
      amazon: flat(0.001),
      otherOnline: flat(0.001),
      grocery: flat(0.033), // 10X CashPoints on BigBasket
      utilities: flat(0.001),
      fuel: flat(0),
      dining: flat(0.033), // Swiggy
      movies: flat(0.033), // BMS
      travel: flat(0.033), // Uber
      offline: flat(0.001),
    },
  },
  {
    id: 'hdfc-shoppers-stop',
    name: 'Shoppers Stop HDFC Bank Credit Card',
    bank: 'HDFC Bank',
    imageUrl: 'https://www.hdfcbank.com/content/api/contentstream-id/723fb80a-2dde-42a3-9793-7ae1be57c87f/418f4a13-863a-4467-a740-1d8486064718/Shoppers%20Stop%20HDFC%20Bank%20Credit%20Card_264x167.png',
    joiningFee: 0,
    annualFee: 0,
    feeWaiver: 'Lifetime Free',
    waiverThreshold: 0,
    joiningBonus: 'Shoppers Stop Voucher',
    features: ['6 First Citizen Points per ₹150 on Private Label Brands', '2 Points on other SS brands', '1% on other spends', 'Lifetime Free'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.004), // 2 pts / 150 * 0.6 value
      amazon: flat(0.004),
      otherOnline: flat(0.004),
      grocery: flat(0.004),
      utilities: flat(0.004),
      fuel: flat(0),
      dining: flat(0.004),
      movies: flat(0.004),
      travel: flat(0.004),
      offline: flat(0.004),
    },
  },
  {
    id: 'hdfc-infinia',
    name: 'HDFC Infinia Metal Edition',
    bank: 'HDFC Bank',
    imageUrl: 'https://www.hdfcbank.com/content/api/contentstream-id/723fb80a-2dde-42a3-9793-7ae1be57c87f/f8d67280-9978-4389-9b97-154df2e21b77/Infinia_Metal_Card_264x167.png',
    joiningFee: 12500,
    annualFee: 12500,
    feeWaiver: 'Waived on ₹10L annual spend',
    waiverThreshold: 1000000,
    joiningBonus: '12,500 Reward Points',
    features: ['3.3% Reward Rate on all spends', 'Up to 33% Rewards on SmartBuy (Flights/Hotels)', 'Unlimited Lounge Access'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.033),
      amazon: flat(0.033),
      otherOnline: flat(0.033),
      grocery: flat(0.033),
      utilities: flat(0.033),
      fuel: flat(0),
      dining: flat(0.033), // Higher on SmartBuy/Dineout (up to 15%)
      movies: flat(0.033),
      travel: flat(0.033), // Higher on SmartBuy
      offline: flat(0.033),
    },
  },
  {
    id: 'hdfc-regalia-gold',
    name: 'HDFC Regalia Gold',
    bank: 'HDFC Bank',
    imageUrl: 'https://www.hdfcbank.com/content/api/contentstream-id/723fb80a-2dde-42a3-9793-7ae1be57c87f/93246a48-18e3-470a-a50d-d5583594b7e8/Regalia%20Gold%20Credit%20Card_264x167.png',
    joiningFee: 2500,
    annualFee: 2500,
    feeWaiver: 'Waived on ₹4L annual spend',
    waiverThreshold: 400000,
    joiningBonus: '₹2500 Gift Voucher',
    features: ['4 Rewards per ₹150 (Approx 1.3%)', '5X on Myntra, Marks & Spencer, Reliance Digital', 'Lounge Access'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.0133),
      amazon: flat(0.0133),
      otherOnline: flat(0.065), // 5X on Myntra
      grocery: flat(0.0133),
      utilities: flat(0.0133),
      fuel: flat(0),
      dining: flat(0.0133),
      movies: flat(0.0133),
      travel: flat(0.0133),
      offline: flat(0.0133),
    },
  },

  // ==================== ICICI BANK ====================
  {
    id: 'icici-amazon',
    name: 'Amazon Pay ICICI Credit Card',
    bank: 'ICICI Bank',
    imageUrl: 'https://www.icicibank.com/content/dam/icicibank/india/managed-assets/images/credit-card/amazon-pay-credit-card.png',
    joiningFee: 0,
    annualFee: 0,
    feeWaiver: 'Lifetime Free',
    waiverThreshold: 0,
    joiningBonus: 'Rewards up to ₹2000',
    features: ['5% Cashback on Amazon (Prime)', '2% on Partner Merchants (Flight/Recharges)', '1% on other spends', 'Lifetime Free'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.01),
      amazon: flat(0.05),
      otherOnline: flat(0.01),
      grocery: flat(0.01),
      utilities: flat(0.02), // Recharges on Amazon
      fuel: flat(0),
      dining: flat(0.01),
      movies: flat(0.01),
      travel: flat(0.02), // Amazon Flights
      offline: flat(0.01),
    },
  },
  {
    id: 'icici-coral',
    name: 'ICICI Coral Credit Card',
    bank: 'ICICI Bank',
    imageUrl: 'https://www.icicibank.com/content/dam/icicibank/india/managed-assets/images/credit-card/coral-credit-card.png',
    joiningFee: 500,
    annualFee: 500,
    feeWaiver: 'Waived on ₹1.5L annual spend',
    waiverThreshold: 150000,
    joiningBonus: '500 Reward Points',
    features: ['2 Reward Points per ₹100 online', '1 Point per ₹100 offline', 'BOGO on Movies (Inox/BookMyShow)'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.005), // ~0.5% value
      amazon: flat(0.005),
      otherOnline: flat(0.005),
      grocery: flat(0.005),
      utilities: flat(0.005),
      fuel: flat(0),
      dining: flat(0.005),
      movies: flat(0.005), // + BOGO
      travel: flat(0.005),
      offline: flat(0.0025),
    },
  },
  {
    id: 'icici-rubyx',
    name: 'ICICI Rubyx Credit Card',
    bank: 'ICICI Bank',
    imageUrl: 'https://www.icicibank.com/content/dam/icicibank/india/managed-assets/images/credit-card/rubyx-credit-card.png',
    joiningFee: 3000,
    annualFee: 2000,
    feeWaiver: 'Waived on ₹2.5L annual spend',
    waiverThreshold: 250000,
    joiningBonus: 'Vouchers worth ₹5000+',
    features: ['4 Rewards per ₹100 online', '2 Rewards per ₹100 offline', '2 Complimentary Domestic Lounge per quarter'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.01), // 4RP * 0.25 = 1%
      amazon: flat(0.01),
      otherOnline: flat(0.01),
      grocery: flat(0.01),
      utilities: flat(0.01),
      fuel: flat(0),
      dining: flat(0.01),
      movies: flat(0.01),
      travel: flat(0.01),
      offline: flat(0.005), // 2RP * 0.25 = 0.5%
    },
  },
  {
    id: 'icici-platinum-chip',
    name: 'ICICI Platinum Chip Card',
    bank: 'ICICI Bank',
    imageUrl: 'https://www.icicibank.com/content/dam/icicibank/india/managed-assets/images/credit-card/instant-platinum-credit-card.png',
    joiningFee: 0,
    annualFee: 0,
    feeWaiver: 'Lifetime Free',
    waiverThreshold: 0,
    joiningBonus: 'None',
    features: ['Lifetime Free', 'Earn Payback Points', '1% Fuel Surcharge Waiver'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.005), // 2 Points per 100
      amazon: flat(0.005),
      otherOnline: flat(0.005),
      grocery: flat(0.005),
      utilities: flat(0.005),
      fuel: flat(0),
      dining: flat(0.005),
      movies: flat(0.005),
      travel: flat(0.005),
      offline: flat(0.005),
    },
  },
  {
    id: 'icici-hpcl',
    name: 'ICICI HPCL Coral',
    bank: 'ICICI Bank',
    imageUrl: 'https://www.icicibank.com/content/dam/icicibank/india/managed-assets/images/credit-card/hpcl-coral-credit-card.png',
    joiningFee: 199,
    annualFee: 199,
    feeWaiver: 'Waived on ₹50k annual spend',
    waiverThreshold: 50000,
    joiningBonus: 'None',
    features: ['2.5% Cashback at HPCL Pumps', '2 Payback Points per ₹100', '1% Fuel Surcharge Waiver'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.005),
      amazon: flat(0.005),
      otherOnline: flat(0.005),
      grocery: flat(0.005),
      utilities: flat(0.005),
      fuel: flat(0.025), // 2.5% at HPCL
      dining: flat(0.005),
      movies: flat(0.005),
      travel: flat(0.005),
      offline: flat(0.005),
    },
  },

  // ==================== IDFC FIRST ====================
  {
    id: 'idfc-wealth',
    name: 'IDFC FIRST Wealth Credit Card',
    bank: 'IDFC FIRST Bank',
    imageUrl: 'https://www.idfcfirstbank.com/content/dam/idfcfirstbank/images/credit-card/wealth-card.png',
    joiningFee: 0,
    annualFee: 0,
    feeWaiver: 'Lifetime Free',
    waiverThreshold: 0,
    joiningBonus: '₹500 Voucher',
    features: ['10X Rewards on Spends > ₹30k', '6X on Online Spends', '3X on Offline Spends', 'Buy 1 Get 1 Movie Ticket'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.015), // 6X = 1.5%
      amazon: flat(0.015),
      otherOnline: flat(0.015),
      grocery: flat(0.015),
      utilities: flat(0.015),
      fuel: flat(0),
      dining: flat(0.015),
      movies: flat(0.015), // + BOGO
      travel: flat(0.015),
      offline: flat(0.0075), // 3X = 0.75%
    },
  },
  {
    id: 'idfc-select',
    name: 'IDFC FIRST Select Credit Card',
    bank: 'IDFC FIRST Bank',
    imageUrl: 'https://www.idfcfirstbank.com/content/dam/idfcfirstbank/images/credit-card/select-card.png',
    joiningFee: 0,
    annualFee: 0,
    feeWaiver: 'Lifetime Free',
    waiverThreshold: 0,
    joiningBonus: '₹500 Voucher',
    features: ['10X Rewards on Spends > ₹25k', '6X on Online Spends', '3X on Offline Spends', 'Lifetime Free'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.0125), // 6X = ~1.25% value on Select
      amazon: flat(0.0125),
      otherOnline: flat(0.0125),
      grocery: flat(0.0125),
      utilities: flat(0.0125),
      fuel: flat(0),
      dining: flat(0.0125),
      movies: flat(0.0125),
      travel: flat(0.0125),
      offline: flat(0.0062), // 3X
    },
  },
  {
    id: 'idfc-millennia',
    name: 'IDFC FIRST Millennia',
    bank: 'IDFC FIRST Bank',
    imageUrl: 'https://www.idfcfirstbank.com/content/dam/idfcfirstbank/images/credit-card/millennia-card.png',
    joiningFee: 0,
    annualFee: 0,
    feeWaiver: 'Lifetime Free',
    waiverThreshold: 0,
    joiningBonus: '₹500 Voucher',
    features: ['10X Rewards on Spends > ₹20k', '6X on Online Spends', 'Lifetime Free'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.0125),
      amazon: flat(0.0125),
      otherOnline: flat(0.0125),
      grocery: flat(0.0125),
      utilities: flat(0.0125),
      fuel: flat(0),
      dining: flat(0.0125),
      movies: flat(0.0125),
      travel: flat(0.0125),
      offline: flat(0.0062),
    },
  },
  {
    id: 'idfc-classic',
    name: 'IDFC FIRST Classic Credit Card',
    bank: 'IDFC FIRST Bank',
    imageUrl: 'https://www.idfcfirstbank.com/content/dam/idfcfirstbank/images/credit-card/classic-card.png',
    joiningFee: 0,
    annualFee: 0,
    feeWaiver: 'Lifetime Free',
    waiverThreshold: 0,
    joiningBonus: '₹500 Voucher',
    features: ['10X Rewards on Spends > ₹20k', '6X on Online Spends', 'Lifetime Free', 'Low Interest Rates'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.0125),
      amazon: flat(0.0125),
      otherOnline: flat(0.0125),
      grocery: flat(0.0125),
      utilities: flat(0.0125),
      fuel: flat(0),
      dining: flat(0.0125),
      movies: flat(0.0125),
      travel: flat(0.0125),
      offline: flat(0.0062),
    },
  },

  // ==================== HSBC & OTHERS ====================
  {
    id: 'hsbc-cashback',
    name: 'HSBC Cashback Credit Card',
    bank: 'HSBC',
    imageUrl: 'https://www.hsbc.co.in/content/dam/hsbc/in/images/credit-cards/cashback-credit-card.png',
    joiningFee: 999,
    annualFee: 999,
    feeWaiver: 'Waived on ₹2L annual spend',
    waiverThreshold: 200000,
    joiningBonus: 'Amazon Voucher ₹1000',
    features: ['10% Cashback on Dining, Food Delivery & Grocery', '1.5% Unlimited on other spends', '4 Complimentary Lounge Visits'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.015),
      amazon: flat(0.015),
      otherOnline: flat(0.015),
      grocery: flat(0.10, 1000), // Cap 1000 combined
      utilities: flat(0.015),
      fuel: flat(0),
      dining: flat(0.10, 1000),
      movies: flat(0.015),
      travel: flat(0.015),
      offline: flat(0.015),
    },
  },
  {
    id: 'amex-mrcc',
    name: 'American Express SmartEarn™',
    bank: 'American Express',
    imageUrl: 'https://icm.aexp-static.com/Internet/InternationalCardShop/va_in/images/cards/SmartEarn_Card.png',
    joiningFee: 495,
    annualFee: 495,
    feeWaiver: 'Waived on ₹40k spend',
    waiverThreshold: 40000,
    joiningBonus: '₹500 cashback',
    features: ['10X Points on Flipkart, Uber, Zomato', '5X on Amazon, Myntra', 'Transact ₹2.5k to earn bonus points'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.025), // ~2.5% effective
      amazon: flat(0.0125), // 5X
      otherOnline: flat(0.005), // Base rate
      grocery: flat(0.005),
      utilities: flat(0.005),
      fuel: flat(0),
      dining: flat(0.025), // Zomato
      movies: flat(0.005),
      travel: flat(0.025), // Uber
      offline: flat(0.005),
    },
  },
  {
    id: 'amex-platinum-travel',
    name: 'American Express Platinum Travel',
    bank: 'American Express',
    imageUrl: 'https://icm.aexp-static.com/Internet/InternationalCardShop/va_in/images/cards/Platinum_Travel.png',
    joiningFee: 3500,
    annualFee: 5000,
    feeWaiver: 'Not applicable',
    waiverThreshold: undefined,
    joiningBonus: '10,000 Points',
    features: ['Spend ₹4L to get ~48,000 worth benefits', '4 Lounges per year', 'Taj Vouchers'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.06), // Effective rate if 4L milestone hit
      amazon: flat(0.06),
      otherOnline: flat(0.06),
      grocery: flat(0.06),
      utilities: flat(0.06),
      fuel: flat(0),
      dining: flat(0.06),
      movies: flat(0.06),
      travel: flat(0.06),
      offline: flat(0.06),
    },
  },
  {
    id: 'sc-smart',
    name: 'Standard Chartered Smart Credit Card',
    bank: 'Standard Chartered',
    imageUrl: 'https://av.sc.com/in/content/images/in-smart-credit-card-400x250.jpg',
    joiningFee: 499,
    annualFee: 499,
    feeWaiver: 'Waived on ₹1.2L spend',
    waiverThreshold: 120000,
    joiningBonus: 'None',
    features: ['2% Cashback on Online Spends', '1% Cashback on Offline Spends', 'Max Cap ₹1000/month'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.02, 1000),
      amazon: flat(0.02, 1000),
      otherOnline: flat(0.02, 1000),
      grocery: flat(0.02, 1000),
      utilities: flat(0.02, 1000),
      fuel: flat(0),
      dining: flat(0.02, 1000),
      movies: flat(0.02, 1000),
      travel: flat(0.02, 1000),
      offline: flat(0.01, 1000),
    },
  },
  {
    id: 'sc-super-value',
    name: 'Standard Chartered Super Value Titanium',
    bank: 'Standard Chartered',
    imageUrl: 'https://av.sc.com/in/content/images/in-super-value-titanium-credit-card-400x250.jpg',
    joiningFee: 750,
    annualFee: 750,
    feeWaiver: 'Waived on ₹90k spend',
    waiverThreshold: 90000,
    joiningBonus: '100% Cashback on Fuel (up to ₹1500)',
    features: ['5% Cashback on Fuel', '5% on Phone Bills', '5% on Utility Bills'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.0033),
      amazon: flat(0.0033),
      otherOnline: flat(0.0033),
      grocery: flat(0.0033),
      utilities: flat(0.05, 500), // 5% Cashback
      fuel: flat(0.05, 500), // 5% Cashback
      dining: flat(0.0033),
      movies: flat(0.0033),
      travel: flat(0.0033),
      offline: flat(0.0033),
    },
  },
  {
    id: 'kotak-myntra',
    name: 'Kotak Myntra Credit Card',
    bank: 'Kotak Mahindra Bank',
    imageUrl: 'https://www.kotak.com/content/dam/Kotak/product_card_images/myntra-kotak-credit-card.png',
    joiningFee: 500,
    annualFee: 500,
    feeWaiver: 'Waived on ₹2L spend',
    waiverThreshold: 200000,
    joiningBonus: '₹500 Myntra Voucher',
    features: ['7.5% Instant Discount on Myntra', '5% on Swiggy, PVR, Cleartrip', '1.25% Unlimited on other spends'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.0125),
      amazon: flat(0.0125),
      otherOnline: flat(0.0125), // Myntra is 7.5%, but average online is lower
      grocery: flat(0.0125),
      utilities: flat(0.0125),
      fuel: flat(0),
      dining: flat(0.05), // Swiggy
      movies: flat(0.05), // PVR
      travel: flat(0.05), // Cleartrip
      offline: flat(0.0125),
    },
  },
  {
    id: 'indusind-legend',
    name: 'IndusInd Bank Legend',
    bank: 'IndusInd Bank',
    imageUrl: 'https://www.indusind.com/content/dam/indusind-platform-images/product-images/personal-banking/cards/credit-cards/legend-credit-card/hero-image/legend-credit-card.png',
    joiningFee: 0,
    annualFee: 0,
    feeWaiver: 'Lifetime Free',
    waiverThreshold: 0,
    joiningBonus: 'Vouchers',
    features: ['Lifetime Free', '2 Points per ₹100 on Weekends', '1 Point per ₹100 Weekdays'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.01), // Avg 1.5% weighted
      amazon: flat(0.01),
      otherOnline: flat(0.01),
      grocery: flat(0.01),
      utilities: flat(0.0075),
      fuel: flat(0),
      dining: flat(0.01),
      movies: flat(0.01), // BOGO
      travel: flat(0.01),
      offline: flat(0.01),
    },
  },
  {
    id: 'indusind-eazydiner',
    name: 'EazyDiner IndusInd Platinum',
    bank: 'IndusInd Bank',
    imageUrl: 'https://www.indusind.com/content/dam/indusind-platform-images/product-images/personal-banking/cards/credit-cards/eazydiner-platinum-credit-card/hero-image/eazydiner-platinum-credit-card.png',
    joiningFee: 1999,
    annualFee: 1999,
    feeWaiver: 'Not applicable',
    waiverThreshold: undefined,
    joiningBonus: 'EazyDiner Prime Membership',
    features: ['Extra 25% OFF on dining via EazyDiner', 'Complimentary Movie Tickets', '2 Reward Points per ₹100'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.005),
      amazon: flat(0.005),
      otherOnline: flat(0.005),
      grocery: flat(0.005),
      utilities: flat(0.005),
      fuel: flat(0),
      dining: flat(0.25), // Huge dining discount
      movies: flat(0.05), // 2 tickets per month
      travel: flat(0.005),
      offline: flat(0.005),
    },
  },
  {
    id: 'yes-cashback',
    name: 'YES Bank Cashback+',
    bank: 'YES Bank',
    imageUrl: 'https://www.yesbank.in/pdf/cashback_plus_credit_card_image.pdf', // Placeholder logic if specific URL fails
    joiningFee: 999,
    annualFee: 999,
    feeWaiver: 'Waived on ₹2.5L spend',
    waiverThreshold: 250000,
    joiningBonus: 'None',
    features: ['5% Cashback on Utility Bills', '2% on other online spends', '1% on offline'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.02),
      amazon: flat(0.02),
      otherOnline: flat(0.02),
      grocery: flat(0.02),
      utilities: flat(0.05, 500), // Cap applies
      fuel: flat(0),
      dining: flat(0.02),
      movies: flat(0.02),
      travel: flat(0.02),
      offline: flat(0.01),
    },
  },
  {
    id: 'rbl-shoprite',
    name: 'RBL Bank ShopRite',
    bank: 'RBL Bank',
    imageUrl: 'https://www.rblbank.com/sites/default/files/images/credit-cards/shoprite-credit-card.png',
    joiningFee: 500,
    annualFee: 500,
    feeWaiver: 'Waived on ₹1L spend',
    waiverThreshold: 100000,
    joiningBonus: '2000 Reward Points',
    features: ['5% Value on Grocery', '10% on Movies', '2.5% Fuel Surcharge Waiver'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.0025),
      amazon: flat(0.0025),
      otherOnline: flat(0.0025),
      grocery: flat(0.05, 500), // 20 pts / 100
      utilities: flat(0.0025),
      fuel: flat(0),
      dining: flat(0.0025),
      movies: flat(0.10, 200),
      travel: flat(0.0025),
      offline: flat(0.0025),
    },
  },
  {
    id: 'au-zenith',
    name: 'AU Zenith Credit Card',
    bank: 'AU Small Finance Bank',
    imageUrl: 'https://www.aubank.in/assets/images/credit-cards/zenith-credit-card-front.png',
    joiningFee: 7999,
    annualFee: 7999,
    feeWaiver: 'Waived on ₹5L spend',
    waiverThreshold: 500000,
    joiningBonus: 'Vouchers worth ₹1000',
    features: ['5X Reward Points on Dining', 'International Lounge Access', 'Low Forex Markup (1.99%)'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.01),
      amazon: flat(0.01),
      otherOnline: flat(0.01),
      grocery: flat(0.01),
      utilities: flat(0.01),
      fuel: flat(0),
      dining: flat(0.025), // 5X
      movies: flat(0.01),
      travel: flat(0.025), // International spend benefit logic
      offline: flat(0.01),
    },
  },
  {
    id: 'citi-cashback',
    name: 'Citi Cashback Credit Card',
    bank: 'Citi / Axis Bank',
    imageUrl: 'https://www.online.citibank.co.in/images/citibank-cashback-credit-card-400x225.jpg',
    joiningFee: 500,
    annualFee: 500,
    feeWaiver: 'Not applicable',
    waiverThreshold: undefined,
    joiningBonus: 'None',
    features: ['5% Cashback on Movie Tickets', '5% on Telephone Bill Payments', '5% on Utility Bill Payments'],
    applyLink: '#',
    rewards: {
      flipkart: flat(0.005),
      amazon: flat(0.005),
      otherOnline: flat(0.005),
      grocery: flat(0.005),
      utilities: flat(0.05, 100), // Cap applies per month
      fuel: flat(0),
      dining: flat(0.005),
      movies: flat(0.05, 100),
      travel: flat(0.005),
      offline: flat(0.005),
    },
  }
];

export const INITIAL_SPENDING_PROFILE: SpendingProfile = {
  flipkart: 0,
  amazon: 0,
  otherOnline: 0,
  grocery: 0,
  utilities: 0,
  fuel: 0,
  dining: 0,
  movies: 0,
  travel: 0,
  offline: 0,
};
